### ISSUE TITLE
Use kubectl get namespace and migrate to new cluster. Explore if this will also migrate a html file linked to the namespace. 

### ISSUE THREAD

**Issue by ylu149** [EC528-Fall-2023/Kubernetes-Artifacts-Cloning#7]

**Comment by Bpleo** [comment]
Extract needed yaml file using kubectl-getNeededInfoCluster, change cluster using kubectl config use-context, and apply the yaml file to the new cluster successfully. Application is up and running

**Comment by Bpleo** [comment]
the function kubectl-getNeededInfoCluster is integraded into kubectl-clone as a function getAllYaml
